### ISSUE TITLE
How to animate the score

### ISSUE THREAD

**Issue by takaaptech** [Xerios/UniRxSimple#1]
Thank you for adding bonus example 4.
I am trying to get a score to increase visually over time (HP Delta)
Something like this https://youtu.be/70_L3EXabGs?t=102

How to do this? Thank so much!

**Comment by Xerios** [comment]
You're welcome :+1: 

This would be more a task for the tweening library. I think some of the libraries offer such feature, but if you don't have that option then I would approach by using their custom tweening fucntionality.

Here's an (untested)example for LeanTween:
```
LeanTween.value(this.gameObject, (val) =>{ textScore.Text = (int)val; },  (int)textScore.Text, newValue, 0.5f)
```

**Comment by takaaptech** [comment]
OK i see it, i will follow that way! Thank so much!
